#!/bin/bash

cd_history() {

	if [ $# -eq 0 ]; then

		if [ ! -s $HOME/.cd_history ]; then
			echo "No directories to choose from, cd into a few directories to build a list!"
			return 1
		else
			source show_history
		fi
	else
		if [ -d "${1}" ]; then
			local PWD
			builtin cd "${1}" || return
			PWD="$(pwd)"
			if ! grep -wq "${PWD}" "$CD_HISTORY_FILE_PATH"; then
				echo "${PWD}" >>"${CD_HISTORY_FILE_PATH}"
			fi
		else
			echo "Directory doesn't exist"
		fi
	fi

}

cd_history "$@"
